# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_profile_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Profile'),
        ),
        migrations.DeleteModel(
            name='Referrer',
        ),
    ]
