# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20160101_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.BankDetail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='case_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.CaseDetail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='res_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.WorkDetail'),
        ),
    ]
