# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20160101_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Profile'),
        ),
    ]
