# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20160101_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='reason_phrase',
        ),
        migrations.AddField(
            model_name='casedetail',
            name='pledged_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='casedetail',
            name='wish_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='brief',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Medical/Health'), (2, 'Education'), (3, 'Other')], default=1),
        ),
    ]
