# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20160306_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='casedetail',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='casedetail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='casedetail',
            name='work',
        ),
        migrations.AddField(
            model_name='address',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
    ]
