# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20160320_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='case',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Contact'),
        ),
    ]
