# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20160320_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
        migrations.AddField(
            model_name='address',
            name='case',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='case',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.CaseDetail'),
        ),
    ]
