# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20160320_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Profile'),
        ),
    ]
