# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_auto_20160406_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(max_length=255, upload_to=donations.models.remitproof_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='casepledge',
            name='remitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remittanceproof',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.CasePledge'),
        ),
    ]
