# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_auto_20160409_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepledge',
            name='txn_ref',
            field=models.TextField(default='', verbose_name='Transaction Details'),
        ),
    ]
