# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_casepledge_txn_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='acc_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Savings'), (2, 'Current')], default=1),
        ),
    ]
