# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0019_bankdetail_acc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='case_details',
        ),
        migrations.AddField(
            model_name='casedetail',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
