# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_auto_20180218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='cheque_copy',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=donations.models.cheque_copy_upload_path),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='postclosure_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postclosure_casedetail', to='photologue.Gallery'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='preclosure_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preclosure_casedetail', to='photologue.Gallery'),
        ),
    ]
